### ISSUE TITLE
Docker image is too large

### ISSUE THREAD

**Issue by Ayedrian** [ls1intum/team-allocator#26]
The docker image is surprisingly large considering the relatively small size of the project (in terms of source code), the `node:lts-bullseye-slim` image is about 200MB, the rest should come from the dependencies especially angular, smaller options are alpine but node might behave differently from what I've heard.

**Comment by Mtze** [comment]
For production/testing usecses it would be best to build the js blob during CI and build a lightweight container that only serves the js blob to the user - That container ca be very small and fast.
