### ISSUE TITLE
Dragging a student from the student pool into an empty team breaks the UI

### ISSUE THREAD

**Issue by Ayedrian** [ls1intum/team-allocator#46]
Sometimes, dragging and dropping a student's card from the person pool into an empty team will lead to the UI glitching out (almost all student cards disappear from the student pool etc.), unfortunately this behavior isn't consistent and somewhat difficult to reproduce. A fix is most likely to switch to a newer drag and drop library.

**Comment by rabeatwork** [comment]
Closed due to https://github.com/ls1intum/team-allocator/pull/56
